import { useEffect, useState } from "react";
import api from "../../services/api";
import { PageTitle } from "../../components/ui/DashboardUi";
function DirectorCreateProject(){
 const [users,setUsers]=useState([]); const [form,setForm]=useState({project_type:'installation',maintenance_cycle_months:1,maintenance_total_times:0}); const [employeeIds,setEmployeeIds]=useState([]); const [file,setFile]=useState(null);
 useEffect(()=>{api.get('/director/select-users').then(r=>setUsers(r.data))},[]);
 const managers=users.filter(u=>u.role==='manager'), customers=users.filter(u=>u.role?.startsWith('customer_')), employees=users.filter(u=>u.role?.startsWith('employee_'));
 const submit=async(e)=>{e.preventDefault();const fd=new FormData();Object.entries(form).forEach(([k,v])=>fd.append(k,v??''));fd.append('employee_ids',employeeIds.join(','));if(file)fd.append('contract_file',file);try{await api.post('/director/projects',fd,{headers:{'Content-Type':'multipart/form-data'}});alert('Tạo dự án thành công');location.href='/director/projects';}catch(err){alert(err.response?.data?.message||'Lỗi tạo dự án')}};
 return <div className="p-8"><PageTitle eyebrow="Giám đốc" title="Tạo dự án" desc="Tạo dự án lắp đặt, bảo trì, sửa chữa và upload hợp đồng PDF."/><form onSubmit={submit} className="card p-6 grid grid-cols-2 gap-4"><Input label="Tên dự án" value={form.name} set={v=>setForm({...form,name:v})}/><div><p className="font-bold mb-2">Loại dự án</p><select className="input" value={form.project_type} onChange={e=>setForm({...form,project_type:e.target.value})}><option value="installation">Lắp đặt</option><option value="maintenance">Bảo trì</option><option value="repair">Sửa chữa</option></select></div><Select label="Khách hàng" value={form.customer_id} set={v=>setForm({...form,customer_id:v})} options={customers}/><Select label="Quản lý" value={form.manager_id} set={v=>setForm({...form,manager_id:v})} options={managers}/><Input label="Địa chỉ công trình" value={form.address} set={v=>setForm({...form,address:v})}/><Input label="Loại thang máy" value={form.elevator_type} set={v=>setForm({...form,elevator_type:v})}/><Input label="Mã hợp đồng" value={form.contract_code} set={v=>setForm({...form,contract_code:v})}/><Input type="date" label="Ngày ký hợp đồng" value={form.contract_date} set={v=>setForm({...form,contract_date:v})}/><Input type="date" label="Ngày bắt đầu" value={form.start_date} set={v=>setForm({...form,start_date:v})}/><Input type="date" label="Ngày kết thúc dự kiến" value={form.expected_end_date} set={v=>setForm({...form,expected_end_date:v})}/><Input type="number" label="Giá trị hợp đồng" value={form.contract_value} set={v=>setForm({...form,contract_value:v})}/><div><p className="font-bold mb-2">File PDF hợp đồng</p><input className="input" type="file" accept="application/pdf" onChange={e=>setFile(e.target.files[0])}/></div>{form.project_type==='maintenance'&&<><Input type="number" label="Số lần bảo trì" value={form.maintenance_total_times} set={v=>setForm({...form,maintenance_total_times:v})}/><Input type="number" label="Chu kỳ bảo trì/tháng" value={form.maintenance_cycle_months} set={v=>setForm({...form,maintenance_cycle_months:v})}/></>}<div className="col-span-2"><p className="font-bold mb-2">Nhân viên phụ trách</p><div className="grid grid-cols-3 gap-3">{employees.map(u=><label key={u.id} className="border rounded-2xl p-3 font-bold"><input type="checkbox" className="mr-2" checked={employeeIds.includes(String(u.id))} onChange={e=>setEmployeeIds(e.target.checked?[...employeeIds,String(u.id)]:employeeIds.filter(id=>id!==String(u.id)) )}/>{u.full_name} <span className="text-slate-400 text-sm">{u.role_label}</span></label>)}</div></div><div className="col-span-2"><p className="font-bold mb-2">Ghi chú</p><textarea className="input" value={form.note||''} onChange={e=>setForm({...form,note:e.target.value})}/></div><button className="btn-primary col-span-2">Tạo dự án</button></form></div>
}
function Input({label,value,set,type='text'}){return <div><p className="font-bold mb-2">{label}</p><input type={type} className="input" value={value||''} onChange={e=>set(e.target.value)}/></div>}
function Select({label,value,set,options}){return <div><p className="font-bold mb-2">{label}</p><select className="input" value={value||''} onChange={e=>set(e.target.value)}><option value="">Chọn</option>{options.map(o=><option key={o.id} value={o.id}>{o.full_name} - {o.role_label}</option>)}</select></div>}
export default DirectorCreateProject;
