import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import api from "../../services/api";
import { PageTitle, Mini, ListItem } from "../../components/ui/DashboardUi";
import { money } from "../../utils/roles";
function Stage({s,onDone}){return <div className={`rounded-2xl border p-4 ${s.status==='doing'?'border-blue-500 bg-blue-50':s.status==='done'?'opacity-55 bg-slate-50':'bg-white'}`}><p className="font-black">{s.stage_order}. {s.stage_name}</p><p className="text-sm text-slate-500 mt-1">{s.status==='done'?'Đã xong':s.status==='doing'?'Đang làm':'Chưa làm'}</p>{s.status!=='done'&&<button className="btn-primary mt-3 py-2" onClick={()=>onDone(s.id)}>Hoàn thành</button>}</div>}
function DirectorProjectDetail(){
 const {id}=useParams(); const [d,setD]=useState(null); const load=async()=>{const r=await api.get(`/director/projects/${id}`);setD(r.data)}; useEffect(()=>{load()},[id]);
 const done=async(stageId)=>{await api.patch(`/director/stages/${stageId}`,{status:'done'});load()};
 if(!d)return <div className="p-8 font-bold">Đang tải...</div>; const {project}=d; const fs=d.financeSummary||{};
 return <div className="p-8"><PageTitle eyebrow={project.project_type_label} title={project.name} desc={`${project.customer_name} • ${project.address}`} action={<Link className="btn-muted" to="/director/projects">Quay lại</Link>}/>
 <div className="grid grid-cols-[1.2fr_1fr] gap-5 mb-5"><div className="card p-5"><h2 className="text-xl font-black mb-4">Thông tin chi tiết</h2><div className="grid grid-cols-2 gap-3"><Mini label="Khách hàng" value={project.customer_name}/><Mini label="SĐT khách" value={project.customer_phone||'-'}/><Mini label="Quản lý" value={project.manager_name||'-'}/><Mini label="SĐT quản lý" value={project.manager_phone||'-'}/><Mini label="Ngày ký" value={project.contract_date}/><Mini label="Dự kiến xong" value={project.expected_end_date}/><Mini label="Loại thang" value={project.elevator_type||'-'}/><Mini label="Tiến độ" value={`${project.progress}%`}/></div>{project.contract_file&&<a className="btn-primary mt-4" href={`http://localhost:5000${project.contract_file}`} target="_blank">Xem hợp đồng PDF</a>}</div><div className="card p-5"><h2 className="text-xl font-black mb-4">Tài chính dự án</h2><div className="space-y-3"><Mini label="Số tiền hợp đồng" value={money(project.contract_value)}/><Mini label="Chi tiêu" value={money(fs.expense)}/><Mini label="Chi phí phát sinh" value={money(fs.extra_expense)}/><Mini label="Còn lại" value={money(fs.balance)}/></div></div></div>
 <div className="card p-5 mb-5"><h2 className="text-xl font-black mb-4">Giai đoạn tiến độ</h2><div className="grid grid-cols-3 gap-3">{d.stages.map(s=><Stage key={s.id} s={s} onDone={done}/>)}</div></div>
 {project.project_type==='maintenance'&&<div className="card p-5 mb-5"><h2 className="text-xl font-black mb-4">Danh sách ngày bảo trì dự kiến</h2><div className="space-y-3">{d.maintenance.map(m=><ListItem key={m.id} title={`Lần ${m.maintenance_no} - ${m.scheduled_date}`} sub={`Nhân viên: ${m.employee_name||'-'} • ${m.note||''}`} right={<span className={m.status==='done'?'badge-green':'badge-orange'}>{m.status==='done'?'Đã bảo trì':'Chưa bảo trì'}</span>}/>)}</div></div>}
 <div className="grid grid-cols-2 gap-5"><div className="card p-5"><h2 className="text-xl font-black mb-4">Báo cáo</h2><div className="space-y-3">{d.reports.map(r=><ListItem key={r.id} title={r.title} sub={`${r.sender_name} • ${r.created_at}`} right={<span className="badge-muted">{r.status}</span>}/>)}</div></div><div className="card p-5"><h2 className="text-xl font-black mb-4">Phát sinh</h2><div className="space-y-3">{d.issues.map(i=><ListItem key={i.id} title={i.title} sub={`${i.sender_name} • ${i.severity}`} right={<span className="badge-red">{i.status}</span>}/>)}</div></div></div>
 </div>
}
export default DirectorProjectDetail;
